# Generated by Django 4.2.4 on 2023-09-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcitvityResponse',
            new_name='ActivityResponse',
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
