# Generated by Django 4.2.4 on 2023-09-01 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activity_formsquestions_formsquestionanswer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormsQuestions',
            new_name='FormsQuestion',
        ),
    ]
