# Generated by Django 4.2.4 on 2023-09-01 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_formsquestions_formsquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormsQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('time_minutes', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formsquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='AcitvityAnswer',
            new_name='AcitvityResponse',
        ),
        migrations.DeleteModel(
            name='FormsQuestionAnswer',
        ),
    ]
