# Generated by Django 4.2.4 on 2023-09-02 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_activity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acitvityresponse',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.activity'),
        ),
        migrations.AlterField(
            model_name='acitvityresponse',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formsquestionresponse',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.formsquestion'),
        ),
        migrations.AlterField(
            model_name='formsquestionresponse',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('academic_degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('country', models.CharField(max_length=255)),
                ('discipline', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
